name: "Security Scan (CodeQL + Dependencies)"

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  dependency-scan:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run npm audit
      run: |
        npm audit --audit-level=moderate --json > audit-results.json || true
        echo "## Dependency Audit Results" >> $GITHUB_STEP_SUMMARY
        npm audit --audit-level=moderate >> $GITHUB_STEP_SUMMARY || true

    - name: Upload audit results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: npm-audit-results
        path: audit-results.json

  codeql-analysis:
    name: CodeQL Security Analysis
    runs-on: ubuntu-latest
    needs: dependency-scan
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g grunt-cli

    - name: Build project for analysis
      run: |
        npm run build

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: javascript-typescript
        config-file: ./.github/codeql/codeql-config.yml

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:javascript-typescript"

    - name: Generate Security Summary
      if: always()
      run: |
        echo "## Security Analysis Complete" >> $GITHUB_STEP_SUMMARY
        echo "- **CodeQL Analysis**: ✅ Using external config (.github/codeql/codeql-config.yml)" >> $GITHUB_STEP_SUMMARY
        echo "- **Query Packs**: Security extended + quality + custom queries" >> $GITHUB_STEP_SUMMARY
        echo "- **Target**: Sealfie landing page (Grunt/Pug/JS)" >> $GITHUB_STEP_SUMMARY
        echo "- **Date**: $(date)" >> $GITHUB_STEP_SUMMARY