name: "Test Local Workflow"
# This workflow is designed for testing with act

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  test-build:
    name: Test Build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm ci
        npm install -g grunt-cli

    - name: Run build
      run: npm run build

    - name: List build output
      run: |
        echo "Build completed successfully"
        ls -la docs/
        
    - name: Test complete
      run: echo "✅ All tests passed!"